package net.vrkknn.andromuks.utils

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.layout.widthIn
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import net.vrkknn.andromuks.AppViewModel

/**
 * Data model for an emoji autocomplete suggestion.
 *
 * - For standard Unicode emojis, [emoji] is populated and [customEmoji] is null.
 * - For custom image emojis, [customEmoji] is populated and [emoji] is null.
 */
data class EmojiSuggestion(
    val shortcode: String,
    val emoji: String? = null,
    val customEmoji: AppViewModel.CustomEmoji? = null
)

/**
 * Static mapping of `:shortcode:` → emoji character.
 *
 * NOTE: This is intentionally focused on the most common emoji shortcodes.
 * It can be expanded over time without changing the autocomplete logic.
 */
object EmojiShortcodes {
    private val shortcodeToEmoji: Map<String, String> = mapOf(
        // Smileys
        "grinning" to "😀",
        "smiley" to "😃",
        "smile" to "😄",
        "grin" to "😁",
        "laughing" to "😆",
        "satisfied" to "😆",
        "sweat_smile" to "😅",
        "joy" to "😂",
        "rofl" to "🤣",
        "slight_smile" to "🙂",
        "upside_down" to "🙃",
        "wink" to "😉",
        "blush" to "😊",
        "innocent" to "😇",
        "heart_eyes" to "😍",
        "star_struck" to "🤩",
        "kissing_heart" to "😘",
        "kissing" to "😗",
        "relaxed" to "☺️",
        "kissing_closed_eyes" to "😚",
        "kissing_smiling_eyes" to "😙",
        "yum" to "😋",
        "stuck_out_tongue" to "😛",
        "stuck_out_tongue_winking_eye" to "😜",
        "zany" to "🤪",
        "stuck_out_tongue_closed_eyes" to "😝",
        "money_mouth" to "🤑",
        "hugs" to "🤗",
        "thinking" to "🤔",
        "zipper_mouth" to "🤐",
        "raised_eyebrow" to "🤨",
        "neutral_face" to "😐",
        "expressionless" to "😑",
        "no_mouth" to "😶",
        "smirk" to "😏",
        "unamused" to "😒",
        "roll_eyes" to "🙄",
        "grimacing" to "😬",
        "relieved" to "😌",
        "pensive" to "😔",
        "sleepy" to "😪",
        "drooling_face" to "🤤",
        "sleeping" to "😴",
        "mask" to "😷",
        "face_with_thermometer" to "🤒",
        "face_with_head_bandage" to "🤕",
        "nauseated_face" to "🤢",
        "vomiting" to "🤮",
        "sneezing_face" to "🤧",
        "hot_face" to "🥵",
        "cold_face" to "🥶",
        "woozy" to "🥴",
        "dizzy_face" to "😵",
        "exploding_head" to "🤯",
        "cowboy" to "🤠",
        "party" to "🥳",
        "sunglasses" to "😎",
        "nerd" to "🤓",
        "monocle" to "🧐",
        "confused" to "😕",
        "slightly_frowning" to "🙁",
        "frowning2" to "☹️",
        "open_mouth" to "😮",
        "hushed" to "😯",
        "astonished" to "😲",
        "flushed" to "😳",
        "pleading" to "🥺",
        "frowning" to "😦",
        "anguished" to "😧",
        "fearful" to "😨",
        "cold_sweat" to "😰",
        "disappointed_relieved" to "😥",
        "cry" to "😢",
        "sob" to "😭",
        "scream" to "😱",
        "confounded" to "😖",
        "persevere" to "😣",
        "disappointed" to "😞",
        "sweat" to "😓",
        "weary" to "😩",
        "tired_face" to "😫",
        "yawning" to "🥱",
        "triumph" to "😤",
        "pout" to "😡",
        "rage" to "😡",
        "angry" to "😠",
        "cursing" to "🤬",

        // Hearts & symbols
        "heart" to "❤️",
        "orange_heart" to "🧡",
        "yellow_heart" to "💛",
        "green_heart" to "💚",
        "blue_heart" to "💙",
        "purple_heart" to "💜",
        "black_heart" to "🖤",
        "white_heart" to "🤍",
        "brown_heart" to "🤎",
        "broken_heart" to "💔",
        "two_hearts" to "💕",
        "revolving_hearts" to "💞",
        "sparkling_heart" to "💖",
        "heartpulse" to "💗",
        "heartbeat" to "💓",
        "cupid" to "💘",

        // Hand gestures
        "thumbsup" to "👍",
        "+1" to "👍",
        "thumbsdown" to "👎",
        "-1" to "👎",
        "ok_hand" to "👌",
        "clap" to "👏",
        "wave" to "👋",
        "raised_hand" to "✋",
        "v" to "✌️",
        "fist" to "✊",
        "punch" to "👊",
        "muscle" to "💪",
        "pray" to "🙏",

        // Common objects / misc
        "fire" to "🔥",
        "100" to "💯",
        "star" to "⭐",
        "star2" to "🌟",
        "sparkles" to "✨",
        "tada" to "🎉",
        "gift" to "🎁",
        "balloon" to "🎈",
        "warning" to "⚠️",
        "check" to "✅",
        "x" to "❌",
        "question" to "❓",
        "grey_question" to "❔",
        "grey_exclamation" to "❕",
        "exclamation" to "❗",

        // Faces with hearts / kisses
        "smiling_face_with_3_hearts" to "🥰",

        // Animals (common)
        "dog" to "🐶",
        "cat" to "🐱",
        "mouse" to "🐭",
        "hamster" to "🐹",
        "rabbit" to "🐰",
        "fox" to "🦊",
        "bear" to "🐻",
        "panda" to "🐼",
        "koala" to "🐨",
        "tiger" to "🐯",
        "lion" to "🦁",
        "cow" to "🐮",
        "pig" to "🐷",
        "frog" to "🐸",
        "monkey" to "🐵",

        // Food (common)
        "pizza" to "🍕",
        "hamburger" to "🍔",
        "fries" to "🍟",
        "hotdog" to "🌭",
        "taco" to "🌮",
        "burrito" to "🌯",
        "coffee" to "☕",
        "tea" to "🍵",
        "beer" to "🍺",
        "wine_glass" to "🍷",
        "cake" to "🍰",
        "birthday" to "🎂",
        
        // Symbols & marks
        "tm" to "™️",
        "copyright" to "©️",
        "registered" to "®️",
        "zero" to "0️⃣",
        "one" to "1️⃣",
        "two" to "2️⃣",
        "three" to "3️⃣",
        "four" to "4️⃣",
        "five" to "5️⃣",
        "six" to "6️⃣",
        "seven" to "7️⃣",
        "eight" to "8️⃣",
        "nine" to "9️⃣",
        "keycap_ten" to "🔟",
        
        // More animals
        "bird" to "🐦",
        "chicken" to "🐔",
        "rooster" to "🐓",
        "penguin" to "🐧",
        "eagle" to "🦅",
        "duck" to "🦆",
        "owl" to "🦉",
        "bat" to "🦇",
        "wolf" to "🐺",
        "boar" to "🐗",
        "horse" to "🐴",
        "unicorn" to "🦄",
        "bee" to "🐝",
        "bug" to "🐛",
        "butterfly" to "🦋",
        "snail" to "🐌",
        "ladybug" to "🐞",
        "ant" to "🐜",
        "spider" to "🕷️",
        "turtle" to "🐢",
        "snake" to "🐍",
        "dragon" to "🐲",
        "sauropod" to "🦕",
        "t_rex" to "🦖",
        "whale" to "🐳",
        "dolphin" to "🐬",
        "fish" to "🐟",
        "tropical_fish" to "🐠",
        "blowfish" to "🐡",
        "shark" to "🦈",
        "octopus" to "🐙",
        "shell" to "🐚",
        "crab" to "🦀",
        "lobster" to "🦞",
        "shrimp" to "🦐",
        "squid" to "🦑",
        "elephant" to "🐘",
        "giraffe" to "🦒",
        "zebra" to "🦓",
        "hippopotamus" to "🦛",
        "rhino" to "🦏",
        "camel" to "🐫",
        "llama" to "🦙",
        "goat" to "🐐",
        "deer" to "🦌",
        "cow2" to "🐄",
        "ox" to "🐂",
        "water_buffalo" to "🐃",
        "ram" to "🐏",
        "sheep" to "🐑",
        "pig2" to "🐖",
        "rat" to "🐀",
        "mouse2" to "🐁",
        "hamster2" to "🐹",
        "rabbit2" to "🐰",
        "chipmunk" to "🐿️",
        "hedgehog" to "🦔",
        "raccoon" to "🦝",
        "badger" to "🦡",
        "sloth" to "🦥",
        "otter" to "🦦",
        "skunk" to "🦨",
        "kangaroo" to "🦘",
        "bison" to "🦬",
        
        // More food
        "apple" to "🍎",
        "green_apple" to "🍏",
        "pear" to "🍐",
        "tangerine" to "🍊",
        "lemon" to "🍋",
        "banana" to "🍌",
        "watermelon" to "🍉",
        "grapes" to "🍇",
        "strawberry" to "🍓",
        "melon" to "🍈",
        "cherries" to "🍒",
        "peach" to "🍑",
        "mango" to "🥭",
        "pineapple" to "🍍",
        "coconut" to "🥥",
        "kiwi" to "🥝",
        "tomato" to "🍅",
        "eggplant" to "🍆",
        "avocado" to "🥑",
        "broccoli" to "🥦",
        "leafy_greens" to "🥬",
        "cucumber" to "🥒",
        "hot_pepper" to "🌶️",
        "corn" to "🌽",
        "carrot" to "🥕",
        "garlic" to "🧄",
        "onion" to "🧅",
        "potato" to "🥔",
        "sweet_potato" to "🍠",
        "bread" to "🍞",
        "croissant" to "🥐",
        "baguette" to "🥖",
        "pretzel" to "🥨",
        "bagel" to "🥯",
        "pancakes" to "🥞",
        "waffle" to "🧇",
        "bacon" to "🥓",
        "cut_of_meat" to "🥩",
        "poultry_leg" to "🍗",
        "meat_on_bone" to "🍖",
        "bone" to "🦴",
        "sandwich" to "🥪",
        "stuffed_flatbread" to "🥙",
        "falafel" to "🧆",
        "taco2" to "🌮",
        "burrito2" to "🌯",
        "tamale" to "🫔",
        "salad" to "🥗",
        "shallow_pan_of_food" to "🥘",
        "fondue" to "🫕",
        "canned_food" to "🥫",
        "spaghetti" to "🍝",
        "steaming_bowl" to "🍜",
        "pot_of_food" to "🍲",
        "curry" to "🍛",
        "sushi" to "🍣",
        "bento" to "🍱",
        "dumpling" to "🥟",
        "oyster" to "🦪",
        "fried_shrimp" to "🍤",
        "rice_ball" to "🍙",
        "rice" to "🍚",
        "rice_cracker" to "🍘",
        "fish_cake" to "🍥",
        "fortune_cookie" to "🥠",
        "moon_cake" to "🥮",
        "oden" to "🍢",
        "dango" to "🍡",
        "shaved_ice" to "🍧",
        "ice_cream" to "🍨",
        "icecream" to "🍦",
        "pie" to "🥧",
        "cupcake" to "🧁",
        "birthday2" to "🎂",
        "custard" to "🍮",
        "lollipop" to "🍭",
        "candy" to "🍬",
        "chocolate_bar" to "🍫",
        "popcorn" to "🍿",
        "doughnut" to "🍩",
        "cookie" to "🍪",
        "chestnut" to "🌰",
        "peanuts" to "🥜",
        "honey_pot" to "🍯",
        "milk" to "🥛",
        "baby_bottle" to "🍼",
        "teapot" to "🫖",
        "coffee2" to "☕",
        "tea2" to "🍵",
        "beverage_box" to "🧃",
        "cup_with_straw" to "🥤",
        "bubble_tea" to "🧋",
        "sake" to "🍶",
        "beer2" to "🍺",
        "beers" to "🍻",
        "champagne_glass" to "🥂",
        "wine_glass2" to "🍷",
        "tumbler_glass" to "🥃",
        "cocktail" to "🍸",
        "tropical_drink" to "🍹",
        "mate" to "🧉",
        "bottle_with_popping_cork" to "🍾",
        "ice" to "🧊",
        
        // Activities & sports
        "soccer" to "⚽",
        "basketball" to "🏀",
        "football" to "🏈",
        "baseball" to "⚾",
        "softball" to "🥎",
        "tennis" to "🎾",
        "volleyball" to "🏐",
        "rugby_football" to "🏉",
        "flying_disc" to "🥏",
        "8ball" to "🎱",
        "ping_pong" to "🏓",
        "badminton" to "🏸",
        "goal_net" to "🥅",
        "golf" to "⛳",
        "ice_skate" to "⛸️",
        "fishing_pole" to "🎣",
        "diving_mask" to "🤿",
        "running_shirt_with_sash" to "🎽",
        "ski" to "🎿",
        "sled" to "🛷",
        "curling_stone" to "🥌",
        "dart" to "🎯",
        "yo_yo" to "🪀",
        "kite" to "🪁",
        "8ball2" to "🎱",
        "crystal_ball" to "🔮",
        "magic_wand" to "🪄",
        "nazar_amulet" to "🧿",
        "video_game" to "🎮",
        "joystick" to "🕹️",
        "slot_machine" to "🎰",
        "game_die" to "🎲",
        "jigsaw" to "🧩",
        "teddy_bear" to "🧸",
        "pinata" to "🪅",
        "nesting_dolls" to "🪆",
        "spade_suit" to "♠️",
        "heart_suit" to "♥️",
        "diamond_suit" to "♦️",
        "club_suit" to "♣️",
        "chess_pawn" to "♟️",
        "joker" to "🃏",
        "mahjong" to "🀄",
        "flower_playing_cards" to "🎴",
        
        // Travel & places
        "red_car" to "🚗",
        "taxi" to "🚕",
        "blue_car" to "🚙",
        "bus" to "🚌",
        "trolleybus" to "🚎",
        "racing_car" to "🏎️",
        "police_car" to "🚓",
        "ambulance" to "🚑",
        "fire_engine" to "🚒",
        "minibus" to "🚐",
        "truck" to "🚚",
        "articulated_lorry" to "🚛",
        "tractor" to "🚜",
        "racing_car2" to "🏎️",
        "motorcycle" to "🏍️",
        "motor_scooter" to "🛵",
        "manual_wheelchair" to "🦽",
        "motorized_wheelchair" to "🦼",
        "auto_rickshaw" to "🛺",
        "bike" to "🚲",
        "kick_scooter" to "🛴",
        "skateboard" to "🛹",
        "roller_skate" to "🛼",
        "busstop" to "🚏",
        "motorway" to "🛣️",
        "railway_track" to "🛤️",
        "oil_drum" to "🛢️",
        "fuelpump" to "⛽",
        "rotating_light" to "🚨",
        "traffic_light" to "🚥",
        "vertical_traffic_light" to "🚦",
        "stop_sign" to "🛑",
        "construction" to "🚧",
        "anchor" to "⚓",
        "ring_buoy" to "🛟",
        "boat" to "⛵",
        "canoe" to "🛶",
        "speedboat" to "🚤",
        "passenger_ship" to "🛳️",
        "ferry" to "⛴️",
        "motor_boat" to "🛥️",
        "ship" to "🚢",
        "airplane" to "✈️",
        "small_airplane" to "🛩️",
        "flight_departure" to "🛫",
        "flight_arrival" to "🛬",
        "parachute" to "🪂",
        "seat" to "💺",
        "helicopter" to "🚁",
        "suspension_railway" to "🚟",
        "mountain_cableway" to "🚠",
        "aerial_tramway" to "🚡",
        "artificial_satellite" to "🛰️",
        "rocket" to "🚀",
        "flying_saucer" to "🛸",
        "bellhop_bell" to "🛎️",
        "luggage" to "🧳",
        "hourglass" to "⌛",
        "hourglass_flowing_sand" to "⏳",
        "watch" to "⌚",
        "alarm_clock" to "⏰",
        "stopwatch" to "⏱️",
        "timer_clock" to "⏲️",
        "mantelpiece_clock" to "🕰️",
        "clock12" to "🕛",
        "clock1230" to "🕧",
        "clock1" to "🕐",
        "clock130" to "🕜",
        "clock2" to "🕑",
        "clock230" to "🕝",
        "clock3" to "🕒",
        "clock330" to "🕞",
        "clock4" to "🕓",
        "clock430" to "🕟",
        "clock5" to "🕔",
        "clock530" to "🕠",
        "clock6" to "🕕",
        "clock630" to "🕡",
        "clock7" to "🕖",
        "clock730" to "🕢",
        "clock8" to "🕗",
        "clock830" to "🕣",
        "clock9" to "🕘",
        "clock930" to "🕤",
        "clock10" to "🕙",
        "clock1030" to "🕥",
        "clock11" to "🕚",
        "clock1130" to "🕦",
        "new_moon" to "🌑",
        "waxing_crescent_moon" to "🌒",
        "first_quarter_moon" to "🌓",
        "moon" to "🌔",
        "full_moon" to "🌕",
        "waning_gibbous_moon" to "🌖",
        "last_quarter_moon" to "🌗",
        "waning_crescent_moon" to "🌘",
        "crescent_moon" to "🌙",
        "new_moon_with_face" to "🌚",
        "first_quarter_moon_with_face" to "🌛",
        "last_quarter_moon_with_face" to "🌜",
        "thermometer" to "🌡️",
        "sunny" to "☀️",
        "full_moon_with_face" to "🌝",
        "sun_with_face" to "🌞",
        "ringed_planet" to "🪐",
        "star3" to "⭐",
        "star4" to "🌟",
        "stars" to "🌠",
        "milky_way" to "🌌",
        "cloud" to "☁️",
        "sun_behind_cloud" to "⛅",
        "cloud_with_lightning_and_rain" to "⛈️",
        "sun_behind_small_cloud" to "🌤️",
        "sun_behind_large_cloud" to "🌥️",
        "sun_behind_rain_cloud" to "🌦️",
        "cloud_with_rain" to "🌧️",
        "cloud_with_snow" to "🌨️",
        "cloud_with_lightning" to "🌩️",
        "tornado" to "🌪️",
        "fog" to "🌫️",
        "wind_face" to "🌬️",
        "cyclone" to "🌀",
        "rainbow" to "🌈",
        "closed_umbrella" to "🌂",
        "open_umbrella" to "☂️",
        "umbrella" to "☔",
        "parasol_on_ground" to "🪷",
        "zap" to "⚡",
        "snowflake" to "❄️",
        "snowman_with_snow" to "☃️",
        "snowman" to "⛄",
        "comet" to "☄️",
        "fire2" to "🔥",
        "droplet" to "💧",
        "ocean" to "🌊",
        
        // Objects
        "eyeglasses" to "👓",
        "dark_sunglasses" to "🕶️",
        "goggles" to "🥽",
        "lab_coat" to "🥼",
        "safety_vest" to "🦺",
        "necktie" to "👔",
        "shirt" to "👕",
        "tshirt" to "👕",
        "jeans" to "👖",
        "scarf" to "🧣",
        "gloves" to "🧤",
        "coat" to "🧥",
        "socks" to "🧦",
        "dress" to "👗",
        "bikini" to "👙",
        "womans_hat" to "👒",
        "tophat" to "🎩",
        "mortar_board" to "🎓",
        "billed_cap" to "🧢",
        "military_helmet" to "🪖",
        "rescue_worker_helmet" to "⛑️",
        "prayer_beads" to "📿",
        "lipstick" to "💄",
        "ring" to "💍",
        "gem" to "💎",
        "mute" to "🔇",
        "speaker" to "🔈",
        "sound" to "🔉",
        "loud_sound" to "🔊",
        "loudspeaker" to "📢",
        "mega" to "📣",
        "postal_horn" to "📯",
        "bell" to "🔔",
        "no_bell" to "🔕",
        "musical_score" to "🎼",
        "musical_note" to "🎵",
        "notes" to "🎶",
        "studio_microphone" to "🎙️",
        "level_slider" to "🎚️",
        "control_knobs" to "🎛️",
        "microphone" to "🎤",
        "headphones" to "🎧",
        "radio" to "📻",
        "saxophone" to "🎷",
        "accordion" to "🪗",
        "guitar" to "🎸",
        "musical_keyboard" to "🎹",
        "trumpet" to "🎺",
        "violin" to "🎻",
        "banjo" to "🪕",
        "drum" to "🥁",
        "long_drum" to "🪘",
        "iphone" to "📱",
        "calling" to "📲",
        "phone" to "☎️",
        "telephone" to "☎️",
        "telephone_receiver" to "📞",
        "pager" to "📟",
        "fax" to "📠",
        "battery" to "🔋",
        "electric_plug" to "🔌",
        "computer" to "💻",
        "desktop_computer" to "🖥️",
        "printer" to "🖨️",
        "keyboard" to "⌨️",
        "computer_mouse" to "🖱️",
        "trackball" to "🖲️",
        "minidisc" to "💽",
        "floppy_disk" to "💾",
        "cd" to "💿",
        "dvd" to "📀",
        "abacus" to "🧮",
        "movie_camera" to "🎥",
        "film_strip" to "🎞️",
        "film_projector" to "📽️",
        "clapper" to "🎬",
        "tv" to "📺",
        "camera" to "📷",
        "camera_flash" to "📸",
        "video_camera" to "📹",
        "vhs" to "📼",
        "mag" to "🔍",
        "mag_right" to "🔎",
        "candle" to "🕯️",
        "bulb" to "💡",
        "flashlight" to "🔦",
        "izakaya_lantern" to "🏮",
        "lantern" to "🪔",
        "diya_lamp" to "🪔",
        "notebook_with_decorative_cover" to "📔",
        "closed_book" to "📕",
        "open_book" to "📖",
        "green_book" to "📗",
        "blue_book" to "📘",
        "orange_book" to "📙",
        "books" to "📚",
        "notebook" to "📓",
        "ledger" to "📒",
        "page_with_curl" to "📃",
        "scroll" to "📜",
        "page_facing_up" to "📄",
        "newspaper" to "📰",
        "newspaper_roll" to "🗞️",
        "bookmark_tabs" to "📑",
        "bookmark" to "🔖",
        "label" to "🏷️",
        "moneybag" to "💰",
        "coin" to "🪙",
        "yen" to "💴",
        "dollar" to "💵",
        "euro" to "💶",
        "pound" to "💷",
        "money_with_wings" to "💸",
        "credit_card" to "💳",
        "receipt" to "🧾",
        "chart" to "💹",
        "envelope" to "✉️",
        "email" to "📧",
        "e_mail" to "📧",
        "incoming_envelope" to "📨",
        "envelope_with_arrow" to "📩",
        "outbox_tray" to "📤",
        "inbox_tray" to "📥",
        "package" to "📦",
        "mailbox" to "📪",
        "mailbox_closed" to "📪",
        "mailbox_with_mail" to "📬",
        "mailbox_with_no_mail" to "📭",
        "postbox" to "📮",
        "ballot_box" to "🗳️",
        "pencil2" to "✏️",
        "black_nib" to "✒️",
        "fountain_pen" to "🖋️",
        "pen" to "🖊️",
        "paintbrush" to "🖌️",
        "crayon" to "🖍️",
        "memo" to "📝",
        "briefcase" to "💼",
        "file_folder" to "📁",
        "open_file_folder" to "📂",
        "card_index_dividers" to "🗂️",
        "date" to "📅",
        "calendar" to "📆",
        "spiral_notepad" to "🗒️",
        "spiral_calendar" to "🗓️",
        "card_index" to "📇",
        "chart_with_upwards_trend" to "📈",
        "chart_with_downwards_trend" to "📉",
        "bar_chart" to "📊",
        "clipboard" to "📋",
        "pushpin" to "📌",
        "round_pushpin" to "📍",
        "paperclip" to "📎",
        "paperclips" to "🖇️",
        "straight_ruler" to "📏",
        "triangular_ruler" to "📐",
        "scissors" to "✂️",
        "card_file_box" to "🗃️",
        "file_cabinet" to "🗄️",
        "wastebasket" to "🗑️",
        "lock" to "🔒",
        "unlock" to "🔓",
        "lock_with_ink_pen" to "🔏",
        "closed_lock_with_key" to "🔐",
        "key" to "🔑",
        "old_key" to "🗝️",
        "hammer" to "🔨",
        "axe" to "🪓",
        "pick" to "⛏️",
        "hammer_and_pick" to "⚒️",
        "hammer_and_wrench" to "🛠️",
        "dagger" to "🗡️",
        "crossed_swords" to "⚔️",
        "gun" to "🔫",
        "boomerang" to "🪃",
        "bow_and_arrow" to "🏹",
        "shield" to "🛡️",
        "carpentry_saw" to "🪚",
        "wrench" to "🔧",
        "screwdriver" to "🪛",
        "nut_and_bolt" to "🔩",
        "gear" to "⚙️",
        "clamp" to "🗜️",
        "balance_scale" to "⚖️",
        "probing_cane" to "🦯",
        "link" to "🔗",
        "chains" to "⛓️",
        "hook" to "🪝",
        "toolbox" to "🧰",
        "magnet" to "🧲",
        "ladder" to "🪜",
        "alembic" to "⚗️",
        "test_tube" to "🧪",
        "petri_dish" to "🧫",
        "dna" to "🧬",
        "microscope" to "🔬",
        "telescope" to "🔭",
        "satellite" to "📡",
        "syringe" to "💉",
        "drop_of_blood" to "🩸",
        "pill" to "💊",
        "adhesive_bandage" to "🩹",
        "stethoscope" to "🩺",
        "door" to "🚪",
        "elevator" to "🛗",
        "mirror" to "🪞",
        "window" to "🪟",
        "bed" to "🛏️",
        "couch_and_lamp" to "🛋️",
        "chair" to "🪑",
        "toilet" to "🚽",
        "plunger" to "🪠",
        "shower" to "🚿",
        "bathtub" to "🛁",
        "mouse_trap" to "🪤",
        "razor" to "🪒",
        "lotion_bottle" to "🧴",
        "safety_pin" to "🪡",
        "broom" to "🧹",
        "basket" to "🧺",
        "roll_of_paper" to "🧻",
        "bucket" to "🪣",
        "soap" to "🧼",
        "toothbrush" to "🪥",
        "sponge" to "🧽",
        "fire_extinguisher" to "🧯",
        "shopping_cart" to "🛒",
        "smoking" to "🚬",
        "coffin" to "⚰️",
        "headstone" to "🪦",
        "funeral_urn" to "⚱️",
        "moyai" to "🗿",
        "placard" to "🪧",
        "atm" to "🏧",
        "put_litter_in_its_place" to "🚮",
        "potable_water" to "🚰",
        "wheelchair" to "♿",
        "mens" to "🚹",
        "womens" to "🚺",
        "restroom" to "🚻",
        "baby_symbol" to "🚼",
        "wc" to "🚾",
        "passport_control" to "🛂",
        "customs" to "🛃",
        "baggage_claim" to "🛄",
        "left_luggage" to "🛅",
        "warning2" to "⚠️",
        "children_crossing" to "🚸",
        "no_entry" to "⛔",
        "no_entry_sign" to "🚫",
        "no_bicycles" to "🚳",
        "no_smoking" to "🚭",
        "do_not_litter" to "🚯",
        "non_potable_water" to "🚱",
        "no_pedestrians" to "🚷",
        "no_mobile_phones" to "📵",
        "underage" to "🔞",
        "radioactive" to "☢️",
        "biohazard" to "☣️",
        "arrow_up" to "⬆️",
        "arrow_upper_right" to "↗️",
        "arrow_right" to "➡️",
        "arrow_lower_right" to "↘️",
        "arrow_down" to "⬇️",
        "arrow_lower_left" to "↙️",
        "arrow_left" to "⬅️",
        "arrow_upper_left" to "↖️",
        "arrow_up_down" to "↕️",
        "left_right_arrow" to "↔️",
        "leftwards_arrow_with_hook" to "↩️",
        "arrow_right_hook" to "↪️",
        "arrow_heading_up" to "⤴️",
        "arrow_heading_down" to "⤵️",
        "arrows_clockwise" to "🔃",
        "arrows_counterclockwise" to "🔄",
        "back" to "🔙",
        "end" to "🔚",
        "on" to "🔛",
        "soon" to "🔜",
        "top" to "🔝",
        "place_of_worship" to "🛐",
        "atom_symbol" to "⚛️",
        "om" to "🕉️",
        "star_of_david" to "✡️",
        "wheel_of_dharma" to "☸️",
        "yin_yang" to "☯️",
        "latin_cross" to "✝️",
        "orthodox_cross" to "☦️",
        "star_and_crescent" to "☪️",
        "peace_symbol" to "☮️",
        "menorah" to "🕎",
        "six_pointed_star" to "🔯",
        "aries" to "♈",
        "taurus" to "♉",
        "gemini" to "♊",
        "cancer" to "♋",
        "leo" to "♌",
        "virgo" to "♍",
        "libra" to "♎",
        "scorpius" to "♏",
        "sagittarius" to "♐",
        "capricorn" to "♑",
        "aquarius" to "♒",
        "pisces" to "♓",
        "ophiuchus" to "⛎",
        "twisted_rightwards_arrows" to "🔀",
        "repeat" to "🔁",
        "repeat_one" to "🔂",
        "arrow_forward" to "▶️",
        "fast_forward" to "⏩",
        "next_track_button" to "⏭️",
        "play_or_pause_button" to "⏯️",
        "arrow_backward" to "◀️",
        "rewind" to "⏪",
        "previous_track_button" to "⏮️",
        "arrow_up_small" to "🔼",
        "arrow_double_up" to "⏫",
        "arrow_down_small" to "🔽",
        "arrow_double_down" to "⏬",
        "pause_button" to "⏸️",
        "stop_button" to "⏹️",
        "record_button" to "⏺️",
        "eject_button" to "⏏️",
        "cinema" to "🎦",
        "low_brightness" to "🔅",
        "high_brightness" to "🔆",
        "signal_strength" to "📶",
        "vibration_mode" to "📳",
        "mobile_phone_off" to "📴",
        "female_sign" to "♀️",
        "male_sign" to "♂️",
        "transgender_symbol" to "⚧️",
        "heavy_multiplication_x" to "✖️",
        "heavy_plus_sign" to "➕",
        "heavy_minus_sign" to "➖",
        "heavy_division_sign" to "➗",
        "infinity" to "♾️",
        "bangbang" to "‼️",
        "interrobang" to "⁉️",
        "question2" to "❓",
        "white_question_mark" to "❔",
        "white_exclamation_mark" to "❕",
        "exclamation2" to "❗",
        "wavy_dash" to "〰️",
        "currency_exchange" to "💱",
        "heavy_dollar_sign" to "💲",
        "medical_symbol" to "⚕️",
        "recycle" to "♻️",
        "fleur_de_lis" to "⚜️",
        "trident" to "🔱",
        "name_badge" to "📛",
        "beginner" to "🔰",
        "o" to "⭕",
        "white_check_mark" to "✅",
        "ballot_box_with_check" to "☑️",
        "heavy_check_mark" to "✔️",
        "x2" to "❌",
        "negative_squared_cross_mark" to "❎",
        "curly_loop" to "➰",
        "loop" to "➿",
        "part_alternation_mark" to "〽️",
        "eight_spoked_asterisk" to "✳️",
        "eight_pointed_black_star" to "✴️",
        "sparkle" to "❇️",
        "copyright2" to "©️",
        "registered2" to "®️",
        "tm2" to "™️",
        "hash" to "#️⃣",
        "asterisk" to "*️⃣",
        "zero2" to "0️⃣",
        "one2" to "1️⃣",
        "two2" to "2️⃣",
        "three2" to "3️⃣",
        "four2" to "4️⃣",
        "five2" to "5️⃣",
        "six2" to "6️⃣",
        "seven2" to "7️⃣",
        "eight2" to "8️⃣",
        "nine2" to "9️⃣",
        "keycap_ten2" to "🔟",
        "capital_abcd" to "🔠",
        "abcd" to "🔡",
        "symbols" to "🔣",
        "abc" to "🔤",
        "a" to "🅰️",
        "ab" to "🆎",
        "b" to "🅱️",
        "cl" to "🆑",
        "cool" to "🆒",
        "free" to "🆓",
        "information_source" to "ℹ️",
        "id" to "🆔",
        "m" to "Ⓜ️",
        "new" to "🆕",
        "ng" to "🆖",
        "o2" to "🅾️",
        "ok" to "🆗",
        "parking" to "🅿️",
        "sos" to "🆘",
        "up" to "🆙",
        "vs" to "🆚",
        "koko" to "🈁",
        "sa" to "🈂️",
        "ideograph_advantage" to "🉐",
        "accept" to "🉑",
        "congratulations" to "㊗️",
        "secret" to "㊙️",
        "u6e80" to "🈵",
        "red_circle" to "🔴",
        "orange_circle" to "🟠",
        "yellow_circle" to "🟡",
        "green_circle" to "🟢",
        "large_blue_circle" to "🔵",
        "purple_circle" to "🟣",
        "brown_circle" to "🟤",
        "black_circle" to "⚫",
        "white_circle" to "⚪",
        "red_square" to "🟥",
        "orange_square" to "🟧",
        "yellow_square" to "🟨",
        "green_square" to "🟩",
        "blue_square" to "🟦",
        "purple_square" to "🟪",
        "brown_square" to "🟫",
        "black_large_square" to "⬛",
        "white_large_square" to "⬜",
        "black_medium_square" to "◼️",
        "white_medium_square" to "◻️",
        "black_medium_small_square" to "◾",
        "white_medium_small_square" to "◽",
        "black_small_square" to "▪️",
        "white_small_square" to "▫️",
        "large_orange_diamond" to "🔶",
        "large_blue_diamond" to "🔷",
        "small_orange_diamond" to "🔸",
        "small_blue_diamond" to "🔹",
        "small_red_triangle" to "🔺",
        "small_red_triangle_down" to "🔻",
        "diamond_shape_with_a_dot_inside" to "💠",
        "radio_button" to "🔘",
        "white_square_button" to "🔳",
        "black_square_button" to "🔲",
        "checkered_flag" to "🏁",
        "triangular_flag_on_post" to "🚩",
        "crossed_flags" to "🎌",
        "black_flag" to "🏴",
        "white_flag" to "🏳️",
        "rainbow_flag" to "🏳️‍🌈",
        "transgender_flag" to "🏳️‍⚧️",
        "pirate_flag" to "🏴‍☠️",
        "flag_ac" to "🇦🇨",
        "flag_ad" to "🇦🇩",
        "flag_ae" to "🇦🇪",
        "flag_af" to "🇦🇫",
        "flag_ag" to "🇦🇬",
        "flag_ai" to "🇦🇮",
        "flag_al" to "🇦🇱",
        "flag_am" to "🇦🇲",
        "flag_ao" to "🇦🇴",
        "flag_aq" to "🇦🇶",
        "flag_ar" to "🇦🇷",
        "flag_as" to "🇦🇸",
        "flag_at" to "🇦🇹",
        "flag_au" to "🇦🇺",
        "flag_aw" to "🇦🇼",
        "flag_ax" to "🇦🇽",
        "flag_az" to "🇦🇿",
        "flag_ba" to "🇧🇦",
        "flag_bb" to "🇧🇧",
        "flag_bd" to "🇧🇩",
        "flag_be" to "🇧🇪",
        "flag_bf" to "🇧🇫",
        "flag_bg" to "🇧🇬",
        "flag_bh" to "🇧🇭",
        "flag_bi" to "🇧🇮",
        "flag_bj" to "🇧🇯",
        "flag_bl" to "🇧🇱",
        "flag_bm" to "🇧🇲",
        "flag_bn" to "🇧🇳",
        "flag_bo" to "🇧🇴",
        "flag_bq" to "🇧🇶",
        "flag_br" to "🇧🇷",
        "flag_bs" to "🇧🇸",
        "flag_bt" to "🇧🇹",
        "flag_bv" to "🇧🇻",
        "flag_bw" to "🇧🇼",
        "flag_by" to "🇧🇾",
        "flag_bz" to "🇧🇿",
        "flag_ca" to "🇨🇦",
        "flag_cc" to "🇨🇨",
        "flag_cd" to "🇨🇩",
        "flag_cf" to "🇨🇫",
        "flag_cg" to "🇨🇬",
        "flag_ch" to "🇨🇭",
        "flag_ci" to "🇨🇮",
        "flag_ck" to "🇨🇰",
        "flag_cl" to "🇨🇱",
        "flag_cm" to "🇨🇲",
        "flag_cn" to "🇨🇳",
        "flag_co" to "🇨🇴",
        "flag_cp" to "🇨🇵",
        "flag_cr" to "🇨🇷",
        "flag_cu" to "🇨🇺",
        "flag_cv" to "🇨🇻",
        "flag_cw" to "🇨🇼",
        "flag_cx" to "🇨🇽",
        "flag_cy" to "🇨🇾",
        "flag_cz" to "🇨🇿",
        "flag_de" to "🇩🇪",
        "flag_dg" to "🇩🇬",
        "flag_dj" to "🇩🇯",
        "flag_dk" to "🇩🇰",
        "flag_dm" to "🇩🇲",
        "flag_do" to "🇩🇴",
        "flag_dz" to "🇩🇿",
        "flag_ea" to "🇪🇦",
        "flag_ec" to "🇪🇨",
        "flag_ee" to "🇪🇪",
        "flag_eg" to "🇪🇬",
        "flag_eh" to "🇪🇭",
        "flag_er" to "🇪🇷",
        "flag_es" to "🇪🇸",
        "flag_et" to "🇪🇹",
        "flag_eu" to "🇪🇺",
        "flag_fi" to "🇫🇮",
        "flag_fj" to "🇫🇯",
        "flag_fk" to "🇫🇰",
        "flag_fm" to "🇫🇲",
        "flag_fo" to "🇫🇴",
        "flag_fr" to "🇫🇷",
        "flag_ga" to "🇬🇦",
        "flag_gb" to "🇬🇧",
        "flag_gd" to "🇬🇩",
        "flag_ge" to "🇬🇪",
        "flag_gf" to "🇬🇫",
        "flag_gg" to "🇬🇬",
        "flag_gh" to "🇬🇭",
        "flag_gi" to "🇬🇮",
        "flag_gl" to "🇬🇱",
        "flag_gm" to "🇬🇲",
        "flag_gn" to "🇬🇳",
        "flag_gp" to "🇬🇵",
        "flag_gq" to "🇬🇶",
        "flag_gr" to "🇬🇷",
        "flag_gs" to "🇬🇸",
        "flag_gt" to "🇬🇹",
        "flag_gu" to "🇬🇺",
        "flag_gw" to "🇬🇼",
        "flag_gy" to "🇬🇾",
        "flag_hk" to "🇭🇰",
        "flag_hm" to "🇭🇲",
        "flag_hn" to "🇭🇳",
        "flag_hr" to "🇭🇷",
        "flag_ht" to "🇭🇹",
        "flag_hu" to "🇭🇺",
        "flag_ic" to "🇮🇨",
        "flag_id" to "🇮🇩",
        "flag_ie" to "🇮🇪",
        "flag_il" to "🇮🇱",
        "flag_im" to "🇮🇲",
        "flag_in" to "🇮🇳",
        "flag_io" to "🇮🇴",
        "flag_iq" to "🇮🇶",
        "flag_ir" to "🇮🇷",
        "flag_is" to "🇮🇸",
        "flag_it" to "🇮🇹",
        "flag_je" to "🇯🇪",
        "flag_jm" to "🇯🇲",
        "flag_jo" to "🇯🇴",
        "flag_jp" to "🇯🇵",
        "flag_ke" to "🇰🇪",
        "flag_kg" to "🇰🇬",
        "flag_kh" to "🇰🇭",
        "flag_ki" to "🇰🇮",
        "flag_km" to "🇰🇲",
        "flag_kn" to "🇰🇳",
        "flag_kp" to "🇰🇵",
        "flag_kr" to "🇰🇷",
        "flag_kw" to "🇰🇼",
        "flag_ky" to "🇰🇾",
        "flag_kz" to "🇰🇿",
        "flag_la" to "🇱🇦",
        "flag_lb" to "🇱🇧",
        "flag_lc" to "🇱🇨",
        "flag_li" to "🇱🇮",
        "flag_lk" to "🇱🇰",
        "flag_lr" to "🇱🇷",
        "flag_ls" to "🇱🇸",
        "flag_lt" to "🇱🇹",
        "flag_lu" to "🇱🇺",
        "flag_lv" to "🇱🇻",
        "flag_ly" to "🇱🇾",
        "flag_ma" to "🇲🇦",
        "flag_mc" to "🇲🇨",
        "flag_md" to "🇲🇩",
        "flag_me" to "🇲🇪",
        "flag_mf" to "🇲🇫",
        "flag_mg" to "🇲🇬",
        "flag_mh" to "🇲🇭",
        "flag_mk" to "🇲🇰",
        "flag_ml" to "🇲🇱",
        "flag_mm" to "🇲🇲",
        "flag_mn" to "🇲🇳",
        "flag_mo" to "🇲🇴",
        "flag_mp" to "🇲🇵",
        "flag_mq" to "🇲🇶",
        "flag_mr" to "🇲🇷",
        "flag_ms" to "🇲🇸",
        "flag_mt" to "🇲🇹",
        "flag_mu" to "🇲🇺",
        "flag_mv" to "🇲🇻",
        "flag_mw" to "🇲🇼",
        "flag_mx" to "🇲🇽",
        "flag_my" to "🇲🇾",
        "flag_mz" to "🇲🇿",
        "flag_na" to "🇳🇦",
        "flag_nc" to "🇳🇨",
        "flag_ne" to "🇳🇪",
        "flag_nf" to "🇳🇫",
        "flag_ng" to "🇳🇬",
        "flag_ni" to "🇳🇮",
        "flag_nl" to "🇳🇱",
        "flag_no" to "🇳🇴",
        "flag_np" to "🇳🇵",
        "flag_nr" to "🇳🇷",
        "flag_nu" to "🇳🇺",
        "flag_nz" to "🇳🇿",
        "flag_om" to "🇴🇲",
        "flag_pa" to "🇵🇦",
        "flag_pe" to "🇵🇪",
        "flag_pf" to "🇵🇫",
        "flag_pg" to "🇵🇬",
        "flag_ph" to "🇵🇭",
        "flag_pk" to "🇵🇰",
        "flag_pl" to "🇵🇱",
        "flag_pm" to "🇵🇲",
        "flag_pn" to "🇵🇳",
        "flag_pr" to "🇵🇷",
        "flag_ps" to "🇵🇸",
        "flag_pt" to "🇵🇹",
        "flag_pw" to "🇵🇼",
        "flag_py" to "🇵🇾",
        "flag_qa" to "🇶🇦",
        "flag_re" to "🇷🇪",
        "flag_ro" to "🇷🇴",
        "flag_rs" to "🇷🇸",
        "flag_ru" to "🇷🇺",
        "flag_rw" to "🇷🇼",
        "flag_sa" to "🇸🇦",
        "flag_sb" to "🇸🇧",
        "flag_sc" to "🇸🇨",
        "flag_sd" to "🇸🇩",
        "flag_se" to "🇸🇪",
        "flag_sg" to "🇸🇬",
        "flag_sh" to "🇸🇭",
        "flag_si" to "🇸🇮",
        "flag_sj" to "🇸🇯",
        "flag_sk" to "🇸🇰",
        "flag_sl" to "🇸🇱",
        "flag_sm" to "🇸🇲",
        "flag_sn" to "🇸🇳",
        "flag_so" to "🇸🇴",
        "flag_sr" to "🇸🇷",
        "flag_ss" to "🇸🇸",
        "flag_st" to "🇸🇹",
        "flag_sv" to "🇸🇻",
        "flag_sx" to "🇸🇽",
        "flag_sy" to "🇸🇾",
        "flag_sz" to "🇸🇿",
        "flag_ta" to "🇹🇦",
        "flag_tc" to "🇹🇨",
        "flag_td" to "🇹🇩",
        "flag_tf" to "🇹🇫",
        "flag_tg" to "🇹🇬",
        "flag_th" to "🇹🇭",
        "flag_tj" to "🇹🇯",
        "flag_tk" to "🇹🇰",
        "flag_tl" to "🇹🇱",
        "flag_tm" to "🇹🇲",
        "flag_tn" to "🇹🇳",
        "flag_to" to "🇹🇴",
        "flag_tr" to "🇹🇷",
        "flag_tt" to "🇹🇹",
        "flag_tv" to "🇹🇻",
        "flag_tw" to "🇹🇼",
        "flag_tz" to "🇹🇿",
        "flag_ua" to "🇺🇦",
        "flag_ug" to "🇺🇬",
        "flag_um" to "🇺🇲",
        "flag_un" to "🇺🇳",
        "flag_us" to "🇺🇸",
        "flag_uy" to "🇺🇾",
        "flag_uz" to "🇺🇿",
        "flag_va" to "🇻🇦",
        "flag_vc" to "🇻🇨",
        "flag_ve" to "🇻🇪",
        "flag_vg" to "🇻🇬",
        "flag_vi" to "🇻🇮",
        "flag_vn" to "🇻🇳",
        "flag_vu" to "🇻🇺",
        "flag_wf" to "🇼🇫",
        "flag_ws" to "🇼🇸",
        "flag_xk" to "🇽🇰",
        "flag_ye" to "🇾🇪",
        "flag_yt" to "🇾🇹",
        "flag_za" to "🇿🇦",
        "flag_zm" to "🇿🇲",
        "flag_zw" to "🇿🇼",
        "flag_england" to "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "flag_scotland" to "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        "flag_wales" to "🏴󠁧󠁢󠁷󠁬󠁳󠁿"
    )

    /**
     * Return autocomplete suggestions for the given [query].
     *
     * Includes both standard emojis and custom emojis from [customEmojiPacks].
     */
    fun getSuggestions(
        query: String,
        customEmojiPacks: List<AppViewModel.EmojiPack>,
        maxResults: Int = 25
    ): List<EmojiSuggestion> {
        val trimmed = query.trim().lowercase()

        val standardMatches = shortcodeToEmoji
            .asSequence()
            .filter { (name, _) ->
                trimmed.isEmpty() || name.startsWith(trimmed)
            }
            .sortedBy { it.key }
            .map { (name, emoji) ->
                EmojiSuggestion(shortcode = name, emoji = emoji)
            }

        val customMatches = customEmojiPacks
            .asSequence()
            .flatMap { it.emojis.asSequence() }
            .filter { emoji ->
                val name = emoji.name.lowercase()
                trimmed.isEmpty() || name.startsWith(trimmed)
            }
            .sortedBy { it.name }
            .map { emoji ->
                EmojiSuggestion(shortcode = emoji.name, customEmoji = emoji)
            }

        return (standardMatches + customMatches)
            .take(maxResults)
            .toList()
    }

    /**
     * Find a completed shortcode (without the surrounding colons), e.g. "laughing".
     */
    fun findByShortcode(
        shortcodeWithoutColons: String,
        customEmojiPacks: List<AppViewModel.EmojiPack>
    ): EmojiSuggestion? {
        val key = shortcodeWithoutColons.trim().lowercase()
        shortcodeToEmoji[key]?.let { emoji ->
            return EmojiSuggestion(shortcode = key, emoji = emoji)
        }

        customEmojiPacks
            .asSequence()
            .flatMap { it.emojis.asSequence() }
            .firstOrNull { it.name.equals(key, ignoreCase = true) }
            ?.let { custom ->
                return EmojiSuggestion(shortcode = custom.name, customEmoji = custom)
            }

        return null
    }
}

/**
 * Floating suggestion list for `:shortcode:` emoji autocomplete.
 */
@Composable
fun EmojiSuggestionList(
    query: String,
    customEmojiPacks: List<AppViewModel.EmojiPack>,
    homeserverUrl: String,
    authToken: String,
    onSuggestionSelected: (EmojiSuggestion) -> Unit,
    modifier: Modifier = Modifier
) {
    val suggestions = remember(query, customEmojiPacks) {
        EmojiShortcodes.getSuggestions(query, customEmojiPacks)
    }

    if (suggestions.isEmpty()) return

    Surface(
        modifier = modifier
            .widthIn(max = 260.dp)
            .border(
                width = 1.dp,
                color = MaterialTheme.colorScheme.outlineVariant,
                shape = RoundedCornerShape(16.dp)
            ),
        shape = RoundedCornerShape(16.dp), // Rounder corners to match user list
        color = MaterialTheme.colorScheme.surface,
        tonalElevation = 8.dp  // Same as user list for consistent appearance
    ) {
        LazyColumn(
            modifier = Modifier
                .height(200.dp), // Same height as user list
            contentPadding = PaddingValues(8.dp),
            verticalArrangement = Arrangement.spacedBy(2.dp)
        ) {
            items(suggestions) { suggestion ->
                Row(
                    modifier = Modifier
                        .clickable { onSuggestionSelected(suggestion) }
                        .padding(horizontal = 12.dp, vertical = 6.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    // Emoji preview
                    Box(
                        modifier = Modifier
                            .width(32.dp)
                            .height(32.dp),
                        contentAlignment = Alignment.Center
                    ) {
                        when {
                            suggestion.emoji != null -> {
                                Text(
                                    text = suggestion.emoji,
                                    style = MaterialTheme.typography.titleLarge
                                )
                            }
                            suggestion.customEmoji != null -> {
                                ImageEmoji(
                                    mxcUrl = suggestion.customEmoji.mxcUrl,
                                    homeserverUrl = homeserverUrl,
                                    authToken = authToken
                                )
                            }
                        }
                    }

                    Spacer(modifier = Modifier.width(12.dp))

                    Text(
                        text = ":${suggestion.shortcode}:",
                        style = MaterialTheme.typography.bodyMedium.copy(fontWeight = FontWeight.Medium),
                        color = MaterialTheme.colorScheme.onSurface
                    )
                }
            }
        }
    }
}


